

#define MSRE_ENABLE_COUNTERS

#define MSRE_ENABLE_LOG
#define MSRE_CONFIG_LOG
#define MSRE_NETWORK_LOG
#define MSRE_RULE_APP_LOG
#define MSRE_GOALS_LOG
#define MSRE_STORE_LOG
#define MSRE_REWRITE_LOOP_LOG

#define MSRE_VERBOSE
#define MSRE_PTR_SCREEN
#define MSRE_HASH_COLLISION_CHECK
